name: $(name)

on:
  schedule:
    - cron: "$(cron)"
  workflow_dispatch:

concurrency:
  group: 'cron'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Start Pinging
        run: node ./src/lib/ping/ping.mjs $(id)
      - name: Update ping records
        run: |
          git pull
          git config --global user.name "Shizu"
          git config --global user.email "<>"
          git add data
          git diff-index --quiet HEAD || git commit -m "Update ping records"
          git push
